### ISSUE TITLE
Graphics unusable after sleep

### ISSUE THREAD

**Issue by velaar** [Colton-Ko/macOS-ThinkPad-X1C6#1]
While sleep (S3) works properly, after sleep there are numerous artifacts on the graphics side. 
Tested with your config and my patched DSDT (for some reason provided DSDT doesn't want to boot).

Works fine after reboot. Any pointers?

**Comment by Colton-Ko** [comment]
@velaar Thank you for reporting. May I ask what is your screen resolution? I suspect this is due to the incompatibility between my configuration (with 2K monitor) and ordinary configuration (1080p monitor).

**Comment by Colton-Ko** [comment]
@velaar I would also like to confirm whether you have installed hidpi patch (onekey-hidpi), as this patch is known to cause display issues after sleep. Thanks!

**Comment by velaar** [comment]
@Colton-Ko Sorry for not getting back earlier. Actually it is resolved now. 
I have found a better ig-platform-id that not only fixes the issue but also solves the sleep/wakeup weird screen problem. 

See here, please test:
https://github.com/tylernguyen/x1c6-hackintosh/issues/22

**Comment by Colton-Ko** [comment]
Thank you! I will merge it into this repo @velaar

**Comment by Colton-Ko** [comment]
Thank you! I have changed the ig-platform-id as well, in previous ig-platform-id I found that my ThinkPad will occasionally reboot during graphics-heavy tasks, it no longer reboots after applying your patches. Than you for your contribution!
